name: app
type: php:8.2
disk: 1024

relationships:
  database: "db:mysql"

web:
  locations:
    "/":
      root: "front"
      index:
        - "index.html"
      allow: true

    "/api":
      root: "back/public"
      passthru: "/index.php"
      allow: true

hooks:
  build: |
    echo "No composer for this project"
