name: vite-gourmand
type: php:8.2

relationships:
  database: "db:mysql"

web:
  locations:
    "/":
      root: "front"
      index:
        - index.html
      allow: true

    "/index.php":
      root: "back/public"
      passthru: "/index.php"
      allow: true

    "/api":
      root: "back/public"
      passthru: "/index.php"
      allow: true