name: vite-gourmand

type: php:8.2

web:
  locations:
    "/":
      root: public
      passthru: /index.php

disk: 512

relationships:
  database: "db:mysql"

mounts:
  "/var/cache": "shared:files/cache"
  "/var/log": "shared:files/log"

hooks:
  build: |
    echo "Build OK"

  deploy: |
    php bin/console doctrine:migrations:migrate --no-interaction || true